#pragma once

#define CHORDAL_HOLD

//#define PERMISSIVE_HOLD
#define TAPPING_TERM 200

#define SPLIT_LAYER_STATE_ENABLE
#define SPLIT_LED_STATE_ENABLE
#define SPLIT_MODS_ENABLE
#define SPLIT_TRANSACTION_IDS_USER CAPS_WORD_SYNC

#ifdef RGB_MATRIX_ENABLE
#    define RGB_MATRIX_DEFAULT_MODE RGB_MATRIX_COMMUNITY_MODULE_PALETTEFX_FLOW
#    define RGB_MATRIX_DEFAULT_HUE 96 // PaletteFx "Synthwave" palette (RGB_MATRIX_HUE_STEP * 12)
#endif
