CAPS_WORD_ENABLE = yes
LAYER_LOCK_ENABLE = yes
MOUSEKEY_ENABLE     = yes
EXTRAKEY_ENABLE     = yes

VIA_ENABLE = yes
LTO_ENABLE = yes
CONSOLE_ENABLE = no

RGBLIGHT_ENABLE = no
RGB_MATRIX_ENABLE = yes
RGB_MATRIX_CUSTOM_USER = yes
