CONVERT_TO = rp2040_ce

RGBLIGHT_ENABLE = no
RGB_MATRIX_ENABLE = yes
CAPS_WORD_ENABLE = yes
LAYER_LOCK_ENABLE = yes
MOUSEKEY_ENABLE = yes
EXTRAKEY_ENABLE = yes

OLED_ENABLE = yes
OLED_DRIVER = ssd1306
WPM_ENABLE = yes

LTO_ENABLE = yes
